### ISSUE TITLE
server task takes 2-7min to complete

### ISSUE THREAD

**Issue by ecerecerez** [netlify/victor-hugo#42] opened 2017-08-30 23:05 UTC
Is it normal to have the server task take 2 to 7 minutes to complete (depends on the machine I use)?

Consider that running  hugo server directly from the site dir takes less than a second.

```terminal
[15:39:29] Finished 'hugo' after 4.65 s
[15:39:29] Starting 'server'...
[15:41:40] Finished 'server' after 2.17 min
[Browsersync] Access URLs:
 -------------------------------------
       Local: http://localhost:3000
    External: http://10.10.40.129:3000
 -------------------------------------
          UI: http://localhost:3001
 UI External: http://10.10.40.129:3001
 -------------------------------------
[Browsersync] Serving files from: ./dist
```
[Edit]
tested by commenting out the 'watch'  subtasks, it looks like the bottleneck is the  gulp watch hugo task.

**Comment by jhabdas** [comment] 2017-08-31 10:50
Hugo bin on its own can tear through 1,000 pps like butter when run on HDD. My take is the JS is the bottleneck as the code isn't compiled – it's interpreted.

**Comment by erquhart** [comment] 2018-01-16 19:04
I've seen very large sites run locally and never anything like this. Can you provide more details so we can reproduce? Is your repo public?

**Comment by ecerecerez** [comment] 2018-02-02 17:01
Sorry @erquhart it isn't public. We use Hugo's partials functionality mostly. Hundreds, maybe a thousand files. 

Here's the latest: [08:57:52] Finished 'hugo' after 6.98 s
[08:57:52] Starting 'server'...
[09:00:18] Finished 'server' after 2.42 min
[BS] Access URLs:
 ----------------------------------------
       Local: http://localhost:3000
    External: http://192.168.103.241:3000
 ----------------------------------------
          UI: http://localhost:3001
 UI External: http://192.168.103.241:3001
 ----------------------------------------
[BS] Serving files from: ./dist

Would sharing the config file help?

**Comment by erquhart** [comment] 2018-02-02 20:54
Considering the number of files you're watching, this might be par for the course. The hugo task I'm using isn't stock, so that takes longer, but the rest is pretty much the same - here's what I'm seeing with a large site, but with considerably less files than yours:

```
Built site for language en:
0 draft content
47 of 47 futures rendered
0 expired content
566 regular pages created
522 other pages created
0 non-page files copied
198 paginator pages created
69 speaker created
0 tags created
115 categories created
0 collections created
56 author created
total in 14600 ms
```
```
[15:51:14] Finished 'hugo' after 34 s
[15:51:14] Starting 'server'...
[15:51:40] Finished 'server' after 26 s
[Browsersync] Access URLs:
 ------------------------------------
       Local: http://localhost:3000
    External: http://192.168.0.9:3000
 ------------------------------------
          UI: http://localhost:3001
 UI External: http://192.168.0.9:3001
 ------------------------------------
[Browsersync] Serving files from: ./dist
```

**Comment by erquhart** [comment] 2018-02-26 18:43
Closing this due to age, comment if you want to revive.

**Closed by erquhart** 2018-02-26 18:43 UTC
