### ISSUE TITLE
Hugo .Kind variable not supported

### ISSUE THREAD

**Issue by jhabdas** [netlify/victor-hugo#16] opened 2017-03-21 20:11 UTC
http://pastebin.com/0fqJBmpW

**Comment by calavera** [comment] 2017-03-21 22:21
This boilerplate doesn't enforce any version of Hugo, are you sure the problem is not with the version you have installed?

It would be great if you respected the issue template we created for the repository, that way people would have a more detailed information about your environment and would be able to assist you better.

**Comment by jhabdas** [comment] 2017-03-22 04:39
Sorry, I don't use Netifly. But your users are hitting this when they take Victor and install new themes. I build AD for 0.16+.

**Comment by darbaga** [comment] 2017-03-24 15:10
Looks like Netlify by default uses Hugo 0.17, which breaks with After Dark. This blog post details how to use a different version:

https://www.adamwills.io/blog/hugo-version-issues-netlify/

**Comment by jhabdas** [comment] 2017-03-24 15:16
Potentially related: https://github.com/spf13/hugo/issues/2689

**Comment by calavera** [comment] 2017-03-26 20:37
As I mentioned before, this issue is not directly related to victor-hugo. Closing.

**Closed by calavera** 2017-03-26 20:37 UTC

**Comment by jhabdas** [comment] 2017-03-26 20:57
It didn't just happen on its own. But you do what you like.
